# Exercício - Mini Projeto de Análise de Dados

Vamos fazer um exercício completo de pandas para um miniprojeto de análise de dados.

Esse exercício vai obrigar a gente a usar boa parte dos conhecimento de pandas e até de outros módulos que já aprendemos ao longo do curso.

### O que temos?

Temos os dados de 2019 de uma empresa de prestação de serviços. 

- CadastroFuncionarios
- CadastroClientes
- BaseServiçosPrestados

Obs1: Para ler arquivos csv, temos o read_csv<br>
Obs2: Para ler arquivos xlsx (arquivos em excel normais, que não são padrão csv), temos o read_excel

### O que queremos saber/fazer?

1. Valor Total da Folha Salarial -> Qual foi o gasto total com salários de funcionários pela empresa? <br>
    Sugestão: calcule o salário total de cada funcionário, salário + benefícios + impostos, depois some todos os salários
    
    
2. Qual foi o faturamento da empresa?<br>
    Sugestão: calcule o faturamento total de cada serviço e depois some o faturamento de todos
    
    
3. Qual o % de funcionários que já fechou algum contrato?<br>
    Sugestão: na base de serviços temos o funcionário que fechou cada serviço. Mas nem todos os funcionários que a empresa tem já fecharam algum serviço.<br>
    . Na base de funcionários temos uma lista com todos os funcionários<br>
    . Queremos calcular Qtde_Funcionarios_Fecharam_Serviço / Qtde_Funcionários_Totais<br>
    . Para calcular a qtde de funcionários que fecharam algum serviço, use a base de serviços e conte quantos funcionários tem ali. Mas lembre-se, cada funcionário só pode ser contado uma única vez.<br><br>
    Dica: se você aplicar o método .unique() em uma variável que é apenas 1 coluna de um dataframe, ele vai excluir todos os valores duplicados daquela coluna.<br>
    Ex: unicos_colunaA = dataframe['colunaA'].unique() te dá como resposta uma lista com todos os itens da colunaA aparecendo uma única vez. Todos os valores repetidos da colunaA são excluidos da variável unicos_colunaA 
    
    
4. Calcule o total de contratos que cada área da empresa já fechou


5. Calcule o total de funcionários por área


6. Qual o ticket médio mensal (faturamento médio mensal) dos contratos?<br>
    Dica: .mean() calcula a média -> exemplo: media_colunaA = dataframe['colunaA'].mean()

Obs: Lembrando as opções mais usuais de encoding:<br>
encoding='latin1', encoding='ISO-8859-1', encoding='utf-8' ou então encoding='cp1252'

Observação Importante: Se o seu código der um erro na hora de importar os arquivos:<br>
- CadastroClientes.csv
- CadastroFuncionarios.csv

Use separador ";" (ponto e vírgula) para resolver

In [136]:
import pandas as pd

tabela_clientes = pd.read_csv('CadastroClientes.csv',sep = ';')
tabela_funcionarios = pd.read_csv('CadastroFuncionarios.csv', sep = ';', decimal = ',')
servicos_prest_df = pd.read_excel('BaseServiçosPrestados.xlsx')
servicos_prest_df = servicos_prest_df.drop(['Unnamed: 4','Unnamed: 5'], axis=1)

 

def custo_salarios():
    salarioBase = tabela_funcionarios['Salario Base'].sum()
    beneficios = tabela_funcionarios['Beneficios'].sum()
    impostos = tabela_funcionarios['Impostos'].sum()
    valorTotal = salarioBase + beneficios + impostos
    print(f'Valor gasto com salario de funcionarios é de R${valorTotal:,.2f}')

def faturamento_empresa():
    servicos_prest_df['Faturamento da Empresa'] = servicos_prest_df['Tempo Total de Contrato (Meses)'] * tabela_clientes['Valor Contrato Mensal']
    faturamento = servicos_prest_df['Faturamento da Empresa'].sum()
    print(f'Faturamento Total da Empresa foi de R$:{faturamento:,.2f}')
    
    

def porcent_vendas():
    fechou_contrato = 0
    qnt_funcionarios = 0
    qnt_vendas = servicos_prest_df['ID Funcionário'].value_counts()
    for v in qnt_vendas:
        fechou_contrato += 1
    for f in tabela_funcionarios['Nome Completo']:
        qnt_funcionarios +=1
    
    print(f'{fechou_contrato/qnt_funcionarios:.2%} dos funcionarios fez alguma venda.')



'''def vendas_area():
    contratos_area_df = servicos_prest_df[['ID Funcionário']].merge(tabela_funcionarios[['ID Funcionário' , 'Area']] , on = 'ID Funcionário')
    contratos_area_qnt = contratos_area_df['Area'].value_counts()
    display(contratos_area_qnt)'''

def funcionarios_area():
    funcionario_area = tabela_funcionarios[['Area']].value_counts()
    #funcionario_area = funcionario_area.plot(figsize =  (10, 5), kind='bar')
    display(funcionario_area)

def media_faturamento_mes():
    tiket_medio = tabela_clientes['Valor Contrato Mensal'].mean()
    print(f'A média do faturamento mensal é R$:{tiket_medio:,.2f}')
    
def venderam_mais():
    venderam_mais_df = servicos_prest_df[['ID Funcionário','Codigo do Servico']].merge(tabela_funcionarios[['Nome Completo','ID Funcionário' ]] , on = 'ID Funcionário')
    venderam_mais = venderam_mais_df[['Nome Completo']].value_counts()
    display(venderam_mais.head())

def salario_real_funcionario():
    tabela_funcionarios['Salario Real'] = tabela_funcionarios['Salario Base'] + tabela_funcionarios['Beneficios'] - tabela_funcionarios['Impostos']
    print('LISTA DE FUNCIONARIOS')
    display(tabela_funcionarios['Nome Completo'][0:21])
    nome = (input('Escolha um nome: '))
    salarioReal = tabela_funcionarios[tabela_funcionarios['Nome Completo'] == nome]
    display(salarioReal[['Nome Completo','Salario Real']])
    
    

salario_real_funcionario()







display(tabela_clientes)
display(tabela_funcionarios)
display(servicos_prest_df)

#media geral de imposto

#media dos beneficios

0             Gabriel Mesquita
1                  João Haddad
2       Amanda Marques Ribeiro
3              Guilherme Nunez
4                Adelino Gomes
5       Audir de Avila Goulart
6              Zilma Guimarães
7                   Gil Bonder
8     Gustavo de Melo Teixeira
9                 Andre Campos
10         André Melo Soledade
11                  Luca Costa
12       Jessica Oliveira Lima
13            Vinicius Freitas
14               Pedro Carrera
15           Isabella Bernardo
16                  Maria Lobo
17                Bruno Vargas
18    Bárbara Spenchutt Vieira
19                 Andre Ramos
20                 Livia Mello
Name: Nome Completo, dtype: object

KeyboardInterrupt: Interrupted by user

In [ ]:
while True:
    print('Escolha uma opção:')
    opcao = int(input(' [1] Custo com salarios\n [2] Funcionarios por Area \n [3] Porcentagem de Funcionarios que efutuaram vendas \n [4] Faturamento Total da Empresa \n [5] Media do Faturamento Mensal\n [6] Funcionarios que mais Venderam \n [7] Salario real de um(a) Funcionario(a) \n [0] Sair \n'))
    
    if opcao == 1:
        custo_salarios()
    if opcao == 2:
        funcionarios_area()
    if opcao == 3:
        porcent_vendas()
    if opcao == 4:
        faturamento_empresa()
    if opcao == 5:
        media_faturamento_mes()
    if opcao == 6:
        venderam_mais()
    if opcao == 7:
        salario_real_funcionario()
    if opcao == 0:
        break

Escolha uma opção:
 [1] Custo com salarios
 [2] Funcionarios por Area
 [3] Porcentagem de Funcionarios que efutuaram vendas
 [4] Faturamento Total da Empresa
 [5] Media do Faturamento Mensal
 [6] Funcionarios que mais Venderam
 [7] Salario real de um(a) Funcionario(a)
 [0] Sair
1
Valor gasto com salario de funcionarios é de R$2,614,343.30
Escolha uma opção:
 [1] Custo com salarios
 [2] Funcionarios por Area
 [3] Porcentagem de Funcionarios que efutuaram vendas
 [4] Faturamento Total da Empresa
 [5] Media do Faturamento Mensal
 [6] Funcionarios que mais Venderam
 [7] Salario real de um(a) Funcionario(a)
 [0] Sair
2

Area
Administrativo    26
Comercial         26
Operações         23
Logística         21
Financeiro        18
dtype: int64

Escolha uma opção:
 [1] Custo com salarios
 [2] Funcionarios por Area
 [3] Porcentagem de Funcionarios que efutuaram vendas
 [4] Faturamento Total da Empresa
 [5] Media do Faturamento Mensal
 [6] Funcionarios que mais Venderam
 [7] Salario real de um(a) Funcionario(a)
 [0] Sair
3
86.84% dos funcionarios fez alguma venda.
Escolha uma opção:
 [1] Custo com salarios
 [2] Funcionarios por Area
 [3] Porcentagem de Funcionarios que efutuaram vendas
 [4] Faturamento Total da Empresa
 [5] Media do Faturamento Mensal
 [6] Funcionarios que mais Venderam
 [7] Salario real de um(a) Funcionario(a)
 [0] Sair
4
Faturamento Total da Empresa foi de R$:5,628,330.00
Escolha uma opção:
 [1] Custo com salarios
 [2] Funcionarios por Area
 [3] Porcentagem de Funcionarios que efutuaram vendas
 [4] Faturamento Total da Empresa
 [5] Media do Faturamento Mensal
 [6] Funcionarios que mais Venderam
 [7] Salario real de um(a) Funcionario(a)
 [0] Sair
5
A média do faturamento mesal é R$:2,502.56
Escolha uma opção:
 [1] Custo com salarios
 [2] Funcionarios por Area
 [3] Porcentagem de Funcionarios que efutuaram vendas
 [4] Faturamento Total da Empresa
 [5] Media do Faturamento Mensal
 [6] Funcionarios que mais Venderam
 [7] Salario real de um(a) Funcionario(a)
 [0] Sair
6

Nome Completo
Rodrigo e Silva Lemos               6
Fernanda Castro Morett Ceppas       5
Guilherme Nunez                     5
Marcos Almeida Albuquerque Faria    5
Fillipe Tupini                      4
dtype: int64

Escolha uma opção:
 [1] Custo com salarios
 [2] Funcionarios por Area
 [3] Porcentagem de Funcionarios que efutuaram vendas
 [4] Faturamento Total da Empresa
 [5] Media do Faturamento Mensal
 [6] Funcionarios que mais Venderam
 [7] Salario real de um(a) Funcionario(a)
 [0] Sair
7

0             Gabriel Mesquita
1                  João Haddad
2       Amanda Marques Ribeiro
3              Guilherme Nunez
4                Adelino Gomes
5       Audir de Avila Goulart
6              Zilma Guimarães
7                   Gil Bonder
8     Gustavo de Melo Teixeira
9                 Andre Campos
10         André Melo Soledade
11                  Luca Costa
12       Jessica Oliveira Lima
13            Vinicius Freitas
14               Pedro Carrera
15           Isabella Bernardo
16                  Maria Lobo
17                Bruno Vargas
18    Bárbara Spenchutt Vieira
19                 Andre Ramos
20                 Livia Mello
Name: Nome Completo, dtype: object

Escolha um nome: Jessica Oliveira Lima

            Nome Completo  Salario Real
12  Jessica Oliveira Lima        1527.4

Escolha uma opção: